-- MySQL Script generated by MySQL Workbench
-- 03/31/15 14:28:18
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema odiseeadministratie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `odiseeadministratie` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `odiseeadministratie` ;

-- -----------------------------------------------------
-- Table `odiseeadministratie`.`studenten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odiseeadministratie`.`studenten` (
  `idstudenten` CHAR(8) NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(65) NOT NULL,
  `chipId` CHAR(16) NOT NULL,
  PRIMARY KEY (`idstudenten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odiseeadministratie`.`docenten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odiseeadministratie`.`docenten` (
  `iddocenten` CHAR(8) NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`iddocenten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odiseeadministratie`.`examens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odiseeadministratie`.`examens` (
  `code` CHAR(6) NOT NULL,
  `naam` VARCHAR(45) NOT NULL,
  `richting` VARCHAR(45) NOT NULL,
  `jaar` VARCHAR(45) NOT NULL,
  `start` DATETIME NOT NULL,
  `einde` DATETIME NOT NULL,
  `aanwezig` TINYINT(1) NULL,
  `studenten_idstudenten` CHAR(8) NOT NULL,
  `docenten_iddocenten` CHAR(8) NOT NULL,
  PRIMARY KEY (`code`, `studenten_idstudenten`, `docenten_iddocenten`),
  INDEX `fk_examens_studenten1_idx` (`studenten_idstudenten` ASC),
  INDEX `fk_examens_docenten1_idx` (`docenten_iddocenten` ASC),
  CONSTRAINT `fk_examens_studenten1`
    FOREIGN KEY (`studenten_idstudenten`)
    REFERENCES `odiseeadministratie`.`studenten` (`idstudenten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_examens_docenten1`
    FOREIGN KEY (`docenten_iddocenten`)
    REFERENCES `odiseeadministratie`.`docenten` (`iddocenten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
